# Generated by Django 3.1.1 on 2020-09-16 12:37

import cards.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSeries',
            fields=[
                ('series', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[cards.validators.validate_series], verbose_name='Card series')),
            ],
        ),
        migrations.CreateModel(
            name='CardNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[cards.validators.validate_numbers], verbose_name='Card number')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Card issue date')),
                ('end_date', models.DateField(verbose_name='Card expiration date')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_numbers', to='cards.cardseries')),
            ],
            options={
                'unique_together': {('series', 'number')},
            },
        ),
    ]
